Repository immobiliare/inca, pull requests merged in 2024-01, with the labels that each got.

#21 Bump checkout and setup-go in actions
  .github/workflows/test.yml
Labels: dependencies

#30 fix(ci): action release now it's ready to run
  .github/CHANGELOG.md
  .github/CONTRIBUTING.md
  .github/workflows/release.yml
Labels: enhancement, github_actions

#37 fix(test): switch the path for unit testing to an absolute one
  cmd/server_test.go
  server/inca_test.go
Labels: bug, testing

#29 feat(provider): support for the HTTP-01 challenge
  Dockerfile
  provider/letsencrypt.go
  server/inca.go
Labels: enhancement
